export const ADD_PRODUCTS = "ADD_PRODUCTS";

export const ADD_SEARCH = "ADD_SEARCH";

export const SELECT_PROD = "SELECT_PROD";

export const ADD_SALES_PRODUCT = "ADD_SALES_PRODUCT";

export const REMOVE_SALES_PRODUCT = "REMOVE_SALES_PRODUCT";

export const REMOVE_ALL_SALES_PRODUCTS = "REMOVE_ALL_SALES_PRODUCTS";

export const UPDATE_PRODUCT = "UPDATE_PRODUCT";

export const DELETE_PRODUCT = "DELETE_PRODUCT";

export const UPDATE_SALES_PRODUCT = "UPDATE_SALES_PRODUCT";

export const SET_DOLAR = "SET_DOLAR";
