export const ADD_PRODUCTS = "ADD_PRODUCTS";

export const ADD_SEARCH = "ADD_SEARCH";

export const SELECT_PROD = "SELECT_PROD";

export const ADD_SALES_PRODUCT = "ADD_SALES_PRODUCT";

export const REMOVE_SALES_PRODUCT = "REMOVE_SALES_PRODUCT";

export const REMOVE_ALL_SALES_PRODUCTS = "REMOVE_ALL_SALES_PRODUCTS";
