const products = [
  {
    id: 1,
    descripcion: "Board Arduino 1",
    prDolar: 16.47,
    ingreso: 7,
  },
  {
    id: 2,
    descripcion: "Board Arduino descripcion larga muy muy largaaaaaaa",
    prDolar: 16.47,
    stock: 5,
    ingreso: 7,
  },
  {
    id: 3,
    descripcion: "Board Arduino 3",
    prDolar: 16.47,
    stock: 5,
    ingreso: 7,
  },
  {
    id: 4,
    descripcion: "Board Arduino 4",
    prDolar: 16.47,
    stock: 5,
    ingreso: 7,
  },
  {
    id: 5,
    descripcion: "Board Arduino 5",
    prDolar: 16.47,
    stock: 5,
    ingreso: 7,
  },
  {
    id: 6,
    descripcion: "Board Arduino 6",
    prDolar: 16.47,
    stock: 5,
    ingreso: 7,
  },
  {
    id: 7,
    descripcion: "Board Arduino 7",
    prDolar: 16.47,
    stock: 5,
    ingreso: 7,
  },
  {
    id: 8,
    descripcion: "Board Arduino 8",
    prDolar: 16.47,
    stock: 5,
    ingreso: 7,
  },
  {
    id: 9,
    descripcion: "Board Arduino 9",
    prDolar: 16.47,
    stock: 5,
    ingreso: 7,
  },
  {
    id: 10,
    descripcion: "Board Arduino 10",
    prDolar: 16.47,
    stock: 5,
    prPesos: 250,
    ingreso: 7,
  },
  {
    id: 11,
    descripcion: "Board Arduino 10",
    prDolar: 16.47,
    stock: 5,
    prPesos: 250,
    ingreso: 7,
  },
  {
    id: 12,
    descripcion: "Board Arduino 10",
    prDolar: 16.47,
    stock: 5,
    ingreso: 7,
  },
  {
    id: 13,
    descripcion: "Board Arduino 10",
    prDolar: 16.47,
    stock: 5,
    prPesos: 250,
    ingreso: 7,
  },
  {
    id: 14,
    descripcion: "Board Arduino 10",
    prDolar: 16.47,
    stock: 5,
    ingreso: 7,
  },
  {
    id: 15,
    descripcion: "Board Arduino 10",
    prDolar: 16.47,
    stock: 5,
    ingreso: 7,
  },
];

export default products;
