const products = [
  {
    id: 1,
    descripcion: "Board Arduino 1",
    precio: 16.47,
    stock: 5,
  },
  {
    id: 2,
    descripcion: "Board Arduino descripcion larga muy muy largaaaaaaa",
    precio: 16.47,
    stock: 5,
  },
  {
    id: 3,
    descripcion: "Board Arduino 3",
    precio: 16.47,
    stock: 5,
  },
  {
    id: 4,
    descripcion: "Board Arduino 4",
    precio: 16.47,
    stock: 5,
  },
  {
    id: 5,
    descripcion: "Board Arduino 5",
    precio: 16.47,
    stock: 5,
  },
  {
    id: 6,
    descripcion: "Board Arduino 6",
    precio: 16.47,
    stock: 5,
  },
  {
    id: 7,
    descripcion: "Board Arduino 7",
    precio: 16.47,
    stock: 5,
  },
  {
    id: 8,
    descripcion: "Board Arduino 8",
    precio: 16.47,
    stock: 5,
  },
  {
    id: 9,
    descripcion: "Board Arduino 9",
    precio: 16.47,
    stock: 5,
  },
  {
    id: 10,
    descripcion: "Board Arduino 10",
    precio: 16.47,
    stock: 5,
  },
  {
    id: 11,
    descripcion: "Board Arduino 10",
    precio: 16.47,
    stock: 5,
  },
  {
    id: 12,
    descripcion: "Board Arduino 10",
    precio: 16.47,
    stock: 5,
  },
  {
    id: 13,
    descripcion: "Board Arduino 10",
    precio: 16.47,
    stock: 5,
  },
  {
    id: 14,
    descripcion: "Board Arduino 10",
    precio: 16.47,
    stock: 5,
  },
  {
    id: 15,
    descripcion: "Board Arduino 10",
    precio: 16.47,
    stock: 5,
  },
  {
    id: 16,
    descripcion: "Board Arduino 10",
    precio: 16.47,
    stock: 5,
  },
  {
    id: 17,
    descripcion: "Board Arduino 10",
    precio: 16.47,
    stock: 5,
  },
  {
    id: 18,
    descripcion: "Board Arduino 10",
    precio: 16.47,
    stock: 5,
  },
  {
    id: 19,
    descripcion: "Board Arduino 10",
    precio: 16.47,
    stock: 5,
  },
  {
    id: 20,
    descripcion: "Board Arduino 10",
    precio: 16.47,
    stock: 5,
  },
  {
    id: 21,
    descripcion: "Board Arduino 10",
    precio: 16.47,
    stock: 5,
  },
  {
    id: 22,
    descripcion: "Board Arduino 10",
    precio: 16.47,
    stock: 5,
  },
  {
    id: 23,
    descripcion: "Board Arduino 10",
    precio: 16.47,
    stock: 5,
  },
  {
    id: 24,
    descripcion: "Board Arduino 10",
    precio: 16.47,
    stock: 5,
  },
  {
    id: 25,
    descripcion: "Board Arduino 10",
    precio: 16.47,
    stock: 5,
  },
];

export default products;
